/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iniciosecion.pruebapdf;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Pacos
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        String rutaInicial = System.getProperty("user.dir");
        
        System.out.println(rutaInicial);
        // Se crea un objeto File que apunte a la carpeta
        File carpeta = new File(rutaInicial, "/documentos");
        if(carpeta.exists()) {
            System.out.println("Carpeta ya existente");
            
        }
        
        if(carpeta.mkdir()) {
            System.out.println("Carpeta creada" + carpeta.getAbsolutePath());
        } else {
            System.out.println("Error al crear carpeta");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarImagen = new javax.swing.JButton();
        nombreArchivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rutaImagen = new javax.swing.JTextField();
        buscarImagen1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Buscar Imagen");

        buscarImagen.setText("Search Image");
        buscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarImagenActionPerformed(evt);
            }
        });

        nombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreArchivoActionPerformed(evt);
            }
        });

        jLabel2.setText("Guardar Archivo (Nombre)");

        rutaImagen.setEditable(false);
        rutaImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutaImagenActionPerformed(evt);
            }
        });

        buscarImagen1.setText("Guardar PDF");
        buscarImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarImagen1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rutaImagen)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(26, 26, 26)
                            .addComponent(nombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buscarImagen1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(buscarImagen)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarImagen))
                .addGap(18, 18, 18)
                .addComponent(rutaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarImagen1))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreArchivoActionPerformed

    private void rutaImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutaImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaImagenActionPerformed

    private void buscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona una imagen");

        // Vamos a filtrar los archivos a visualizar (imagenes en este caso)
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                // Permitir solo archivos con extensiones de imagen
                String name = f.getName().toLowerCase();
                return f.isDirectory() || name.endsWith(".jpg") || name.endsWith(".jpeg") ||
                       name.endsWith(".png") || name.endsWith(".gif") || name.endsWith(".bmp");
            }

            @Override
            public String getDescription() {
                return "Archivos de imagen (*.jpg, *.jpeg, *.png, *.gif, *.bmp)";
            }
        });

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();

            rutaImagen.setText(filePath); // a rutaImagen le asignamos su valor

           
            JOptionPane.showMessageDialog(this, "Imagen seleccionada: " + filePath);
        }
    }//GEN-LAST:event_buscarImagenActionPerformed

    private void buscarImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarImagen1ActionPerformed
        // TODO add your handling code here:
        String rutaInicial = System.getProperty("user.dir");
        String[] encabezados = {"ID", "Nombre", "Apellido"};
        String[][] datos = {
                {"1", "Jose", "Aldana"},
                {"2", "Pablo", "Robles"}
        };
        // System.out.println(rutaImagen.getText());
        if (!nombreArchivo.getText().isEmpty()) {
            String nombre = nombreArchivo.getText();

            
            if (!nombre.toLowerCase().endsWith(".pdf")) {
                nombre = nombre + ".pdf";
                nombreArchivo.setText(nombre);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo de nombre está vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            GeneradorPDF pdf = new GeneradorPDF();
            pdf.generarPDF(rutaInicial + "/documentos/" + nombreArchivo.getText(), encabezados, datos, rutaImagen.getText(), "Hola", "Este es un ejemplo");
         
            System.out.println("Archivo creado exitosamente");
        } catch (MalformedURLException  e) {
            System.out.println("Ruta imagen invalida");
            e.printStackTrace();
        } catch (IOException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarImagen1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarImagen;
    private javax.swing.JButton buscarImagen1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombreArchivo;
    private javax.swing.JTextField rutaImagen;
    // End of variables declaration//GEN-END:variables
}
